const express = require("express");
const controller = require("../controllers/salesOrderController");
const { requireRole } = require("../middleware/authMiddleware");
const router = express.Router();
router.get("/", requireRole("admin", "accountant", "contact"), controller.list);
router.post("/", requireRole("admin", "accountant"), controller.create);
router.get("/:salesOrderId/lines", requireRole("admin", "accountant", "contact"), controller.listLines);
router.post("/:salesOrderId/lines", requireRole("admin", "accountant"), controller.createLine);
router.get("/:salesOrderId/lines/:id", requireRole("admin", "accountant", "contact"), controller.getLine);
router.put("/:salesOrderId/lines/:id", requireRole("admin", "accountant"), controller.updateLine);
router.delete("/:salesOrderId/lines/:id", requireRole("admin", "accountant"), controller.removeLine);
router.post("/:id/convert-to-invoice", requireRole("admin", "accountant"), controller.convertToInvoice);
router.get("/:id", requireRole("admin", "accountant", "contact"), controller.get);
router.put("/:id", requireRole("admin", "accountant"), controller.update);
router.delete("/:id", requireRole("admin", "accountant"), controller.remove);
module.exports = router;
